### ISSUE TITLE
DateSelectedEvent contains wrong date

### ISSUE THREAD

**Issue by mikboe** [FlowingCode/YearMonthCalendarAddon#18]
If i click on a date in the yearcalendar, the DateSelectedEvent always contains the date prior to this day.
e.g. if i click on 1.1.2022 the date in the event is 31.12.2021
I checked your demo and there the behaviour is the same.
If i click on e.g. 1.1.2022 the output is "Selected date: 2021-12-31"

**Comment by javier-godoy** [comment]
Hello. I think this issue may be related to timezones. What is the timezone in your computer? (The demo server has UTC-3. It shouldn't affect the component, but maybe there is a wrong conversion in the component.) 

![image](https://user-images.githubusercontent.com/11554739/183956175-6650a868-6772-474c-84a3-f2cd07d7de5e.png)

**Comment by mikboe** [comment]
Timezone here is UTC+2
But I have the same behaviour, if I run a spring boot app with the component and the browser on the same system.
The problem seems to be in the web component part, cause I debugged into DateSelectedEvent and @EventData("event.detail.value") String date allready contained 2021-12-31
If there is a conversion it allready happens on client side

**Comment by mikboe** [comment]
Found the location of the conversion. You use toISOString(), which applies timezone conversion to the created date object. Since the time in the date object ist 0:00 for all timzones with a positive offset this will result in a converted date one day in the past.

**Comment by javier-godoy** [comment]
Thanks for reporting this issue and for the detailed analysis, The fix has been released in version [2.1.1](https://vaadin.com/directory/component/year-month-calendar-add-on/2.1.1)
