### ISSUE TITLE
Failed to resolve delegate-focus-mixin in Vaadin 24.0.0.alpha7

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/YearMonthCalendarAddon#48]
DelegateFocusMixin has been moved to component-base in Vaadin 24.0.0.alpha7 (https://github.com/vaadin/web-components/pull/5181)
```
Rollup failed to resolve import "@vaadin/field-base/src/delegate-focus-mixin.js" from "/var/jenkins/workspace/AddonsDemo-v24/frontend/generated/jar-resources/fc-month-calendar/shadow-focus-mixin.js".
```

**Comment by javier-godoy** [comment]
Given this change, we will have to release a new major version for Vaadin 24

**Comment by mlopezFC** [comment]
Reopening this so the fix can be applied to the correct branch.
