### ISSUE TITLE
Bug with MonthCalendar ClassNameGenerator

### ISSUE THREAD

**Issue by Jukisawa** [FlowingCode/YearMonthCalendarAddon#58]
If i change the Style of the First of January in 2023 and go to february in 2023 then the first field wich dont have a date its still has the changed style.

**Comment by javier-godoy** [comment]
Confirmed. (Reproduced with version 2.3.0 in Vaadin 22)

This is related to #32 (which has been fixed for `YearCalendar`)

#### Example to reproduce
```
    MonthCalendar calendar = new MonthCalendar(YearMonth.now());

    calendar.setClassNameGenerator(date -> {
      return date.getDayOfMonth() == 1 ? "holiday" : null;
    });

    add(calendar, new Button("+", ev -> {
      calendar.setYearMonth(calendar.getYearMonth().plus(1, ChronoUnit.MONTHS));
    }));
```

**Comment by javier-godoy** [comment]
Please try 2.3.1-SNAPSHOT from https://maven.flowingcode.com/snapshots/ repository
