### ISSUE TITLE
MonthCalendar is not supporting i18n

### ISSUE THREAD

**Issue by The-JurB** [FlowingCode/YearMonthCalendarAddon#78]
### Describe the bug

The MonthCalendar is not supporting the i18n.
If i set the i18n on the compenent, nothing is changed, it uses the default settings.

If i set the same i18n on the YearCalendar, it works perfectly.
![yearcalendar_i18n](https://github.com/FlowingCode/YearMonthCalendarAddon/assets/171923369/bdf45e21-8e55-4cee-a063-0367fb377476)
![monthCalendar_no_i18n](https://github.com/FlowingCode/YearMonthCalendarAddon/assets/171923369/9828f895-b9f0-4678-a559-5efbd3dce418)

### Expected behavior

I expect the MonthCalender to also support the i18n just like the YearCalendar

### Add-on Version

4.2.0

### Vaadin Version

24.3.10

**Comment by javier-godoy** [comment]
Confirmed. I18N support in MonthCalendar does not work:
```
    MonthCalendar calendar = new MonthCalendar(YearMonth.now());
    DatePickerI18n i18n = new DatePickerI18n();
    DateFormatSymbols dfs = DateFormatSymbols.getInstance(Locale.FRENCH);
    i18n.setMonthNames(List.of(dfs.getMonths()));
    i18n.setWeekdays(List.of(dfs.getWeekdays()));
    calendar.setI18n(i18n);
```

But I18N support in YearCalendar works as expected:
```
    YearCalendar calendar = new YearCalendar();
    DatePickerI18n i18n = new DatePickerI18n();
    DateFormatSymbols dfs = DateFormatSymbols.getInstance(Locale.FRENCH);
    i18n.setMonthNames(List.of(dfs.getMonths()));
    i18n.setWeekdays(List.of(dfs.getWeekdays()));
    i18n.setWeekdaysShort(List.of(dfs.getShortWeekdays()));
    calendar.setI18n(i18n);
```
